### ISSUE TITLE
1.2.0 fails with an unhandled exception from server error 422

### ISSUE THREAD

**Issue by unitysipu** [snyk-tech-services/snyk-prevent-gh-commit-status#12]
```
# snyk-prevent-gh-commit-status snyk_test_results.json $(cat ~/.secrets/github/snyk) Unity-Technologies a030ac63248df50524b71aa805a591683f65e4ee -d
  snyk inline mode +0ms
  snyk Verify input data for JSON structure +1ms
Snyk API - Could not find a monitored project matching.                                               Make sure to specify the right org when snyk test using --org
snyk-delta will return exit code 1 if any vulns are found in the current project
  snyk Retrieve Snyk Project  in org sandbox-mdm +959ms

Debug Mode


New issue introduced !
Security Vulnerability:

  1/1: Improper Certificate Validation [Medium Severity]
    Via: requests@2.25.1 => urllib3@1.26.3
    Fixed in: urllib3 1.26.4



New issues introduced !
License Issues:
  1/2: MPL-2.0 license [Medium Severity]
    Via: requests@2.25.1 => certifi@2020.12.5 

  2/2: LGPL-2.1 license [Medium Severity]
    Via: requests@2.25.1 => chardet@4.0.0 

(node:833) UnhandledPromiseRejectionWarning: Error: Error: Request failed with status code 422
    at main (/snapshot/project/dist/index.js:90:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:833) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by unitysipu** [comment]
Attaching json [snyk_test_results.zip](https://github.com/snyk-tech-services/snyk-prevent-gh-commit-status/files/6391006/snyk_test_results.zip)

**Comment by unitysipu** [comment]
looks like the issue is the deprectated -d parameter, however i suppose the unhandled exception could be handled

**Comment by aarlaud** [comment]
Creating a task to handle, closing this issue otherwise.
