### ISSUE TITLE
snyk-prevent-gh-commit-status fails to parse org properly from --json-file-output

### ISSUE THREAD

**Issue by unitysipu** [snyk-tech-services/snyk-prevent-gh-commit-status#3]
providing a results.json file for snyk-prevent-gh-commit-status, the tool seems to fail in parsing the json output for the correct org name:

The link in my github checks points to "https://app.snyk.io/org/undefined/projects"

> snyk version
1.561.0 (standalone)

```
RESULTFILE="/tmp/snyk_test_results.json"
GH_ORG_NAME=$(getGitMeta ORG)
GH_REPO_NAME=$(basename -s .git "$(getGitMeta REPO)")

snyk test -d --all-projects --json-file-output="${RESULTFILE}" "$@" || echo "INFO: Snyk test complete, status: $(grep $? < /snyk/snyk_status_codes)"

snyk-prevent-gh-commit-status "${RESULTFILE}" "${SNYK_GITHUB_TOKEN}" "${GH_ORG_NAME}" "${GH_REPO_NAME}" "${GIT_COMMIT}" -d

```

I can see from the json file that it has the correct org name in it:

```
    "ok": false,
    "dependencyCount": 30,
    "org": "sandbox-mdm",
    "policy": "# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.\nversion: v1.19.0\nignore: {}\npatch: {}\n",
    "isPrivate": true,
    "licensesPolicy": ...

```

The tool outputs this in debug mode:

```
snyk inline mode +0ms
  snyk Verify input data for JSON structure +1ms
  snyk ERROR: NotFoundError: Error: Request failed with status code 404
    at Object.makeSnykRequest (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/request.ts:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object._makeRequest [as next] (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/requestManager.ts:67:28) {
  data: {
    code: 404,
    message: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).',
    error: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).'
  }
} +0ms
  snyk ERROR: NotFoundError: Error: Request failed with status code 404
    at Object.makeSnykRequest (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/request.ts:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object._makeRequest [as next] (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/requestManager.ts:67:28) {
  data: {
    code: 404,
    message: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).',
    error: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).'
  }
} +262ms
  snyk ERROR: NotFoundError: Error: Request failed with status code 404
    at Object.makeSnykRequest (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/request.ts:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object._makeRequest [as next] (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/requestManager.ts:67:28) {
  data: {
    code: 404,
    message: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).',
    error: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).'
  }
} +261ms
  snyk ERROR: NotFoundError: Error: Request failed with status code 404
    at Object.makeSnykRequest (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/request.ts:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object._makeRequest [as next] (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/requestManager.ts:67:28) {
  data: {
    code: 404,
    message: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).',
    error: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).'
  }
} +256ms
  snyk ERROR: NotFoundError: Error: Request failed with status code 404
    at Object.makeSnykRequest (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/request.ts:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object._makeRequest [as next] (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/requestManager.ts:67:28) {
  data: {
    code: 404,
    message: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).',
    error: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).'
  }
} +227ms
  snyk ERROR: NotFoundError: Error: Request failed with status code 404
    at Object.makeSnykRequest (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/request.ts:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object._makeRequest [as next] (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/requestManager.ts:67:28) {
  data: {
    code: 404,
    message: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).',
    error: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).'
  }
} +252ms
  snyk ERROR: NotFoundError: Error: Request failed with status code 404
    at Object.makeSnykRequest (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/request.ts:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object._makeRequest [as next] (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/requestManager.ts:67:28) {
  data: {
    code: 404,
    message: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).',
    error: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).'
  }
} +257ms
  snyk ERROR: NotFoundError: Error: Request failed with status code 404
    at Object.makeSnykRequest (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/request.ts:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object._makeRequest [as next] (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/requestManager.ts:67:28) {
  data: {
    code: 404,
    message: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).',
    error: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).'
  }
} +296ms
  snyk ERROR: NotFoundError: Error: Request failed with status code 404
    at Object.makeSnykRequest (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/request.ts:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object._makeRequest [as next] (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/requestManager.ts:67:28) {
  data: {
    code: 404,
    message: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).',
    error: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).'
  }
} +245ms
  snyk ERROR: NotFoundError: Error: Request failed with status code 404
    at Object.makeSnykRequest (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/request.ts:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object._makeRequest [as next] (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/requestManager.ts:67:28) {
  data: {
    code: 404,
    message: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).',
    error: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).'
  }
} +251ms
  snyk ERROR: NotFoundError: Error: Request failed with status code 404
    at Object.makeSnykRequest (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/request.ts:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object._makeRequest [as next] (/usr/lib/node_modules/snyk-delta/node_modules/snyk-request-manager/src/lib/request/requestManager.ts:67:28) {
  data: {
    code: 404,
    message: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).',
    error: 'Org projects was not found or you may not have the correct permissions to access the org.\n' +
      'You can use the following orgs: sandbox-mdm (36629525-299b-4647-af97-19ae234d50c2).'
  }
} +244ms
  snyk Error: NotFoundError: Error: Request failed with status code 404
  snyk     at Projects.post (/usr/lib/node_modules/snyk-delta/node_modules/snyk-api-ts-client/src/lib/client/generated/org.ts:1930:15)
  snyk     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  snyk     at Object.getProjectUUID (/usr/lib/node_modules/snyk-delta/src/lib/snyk/snyk.ts:16:23)
  snyk     at Object.getDelta (/usr/lib/node_modules/snyk-delta/src/lib/index.ts:63:27)
  snyk     at main (/usr/lib/node_modules/snyk-prevent-gh-commit-status/src/lib/index.ts:37:20) +0ms
```

**Comment by unitysipu** [comment]
attached the json result file
[snyk_test_results.zip](https://github.com/snyk-tech-services/snyk-prevent-gh-commit-status/files/6344703/snyk_test_results.zip)

**Comment by aarlaud** [comment]
ACK. will check this shortly.

**Comment by aarlaud** [comment]
oh just noticed, I don't believe this is compatible with --all-projects. I'll need to double check and see how we can accomodate this. try one projects at the time for now.

**Comment by unitysipu** [comment]
that's not going to work in our use case, unfortunately. my wrapper needs to be indifferent and handle both monorepos and simple ones

**Comment by aarlaud** [comment]
Going to make it work. Will work on this today.

**Comment by aarlaud** [comment]
v1.1.0 should do the trick. Please open an issue if something doesn't work as expected.

**Comment by unitysipu** [comment]
still doesn't work:

```
# snyk-prevent-gh-commit-status snyk_test_results.json $SNYK_GITHUB_TOKEN Unity-Technologies mz-jenkins-testing
/usr/bin/snyk-prevent-gh-commit-status: line 1: --2021-04-22: command not found
/usr/bin/snyk-prevent-gh-commit-status: line 2: syntax error near unexpected token `('
/usr/bin/snyk-prevent-gh-commit-status: line 2: `Resolving github.com (github.com)... 140.82.121.3'

```

**Comment by unitysipu** [comment]
please try the json file i provided in that zip attachment, you should see the same issue with that one

**Comment by unitysipu** [comment]
hmm, looks like it runs better on my desktop (albeit shows a complaint)
```
➜  mz-jenkins-testing git:(snyk) ✗ ./snyk-prevent-gh-commit-status ./snyk_test_results.json $(cat ~/.secrets/github/snyk) Unity-Technologies mz-jenkins-testing -d
  snyk inline mode +0ms
  snyk Verify input data for JSON structure +1ms
  snyk Retrieve Snyk Project d52f1f9a-9de0-4ff7-9c70-998886f3af30 in org sandbox-mdm +912ms
  snyk Monitored snapshot had 1 vulns +271ms
  snyk Tested project has 1 vulns +0ms
  snyk Severity threshold  1 low +0ms
  snyk Monitored snapshot had 2 license issues +1ms
  snyk Tested project has 2 license issues +0ms
  snyk Severity threshold  1 low +0ms
  snyk New Vulns count =0 +0ms
  snyk New Licenses Issues count =0 +0ms
No new issues found !
(node:13750) UnhandledPromiseRejectionWarning: Error: Error: Request failed with status code 422
    at main (/snapshot/project/dist/index.js:86:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13750) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:13750) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by unitysipu** [comment]
it also gives a "missing argument" error if run without the -d flag

```
# ./snyk-prevent-gh-commit-status ./snyk_test_results.json $SNYK_GITHUB_TOKEN Unity-Technologies mz-jenkins-testing   
error missing argument

```

**Comment by unitysipu** [comment]
looks like it's working otherwise, once i got my credentials in order
